version: '3.7'
services:
  xcache:
    build: .
    #image: dciangot/test:latest
    expose:
    - 8443
    volumes:
    - /tmp/x509up_u02:/tmp/x509up_u02
    hostname: condemand01.pic.es
    environment:
      XRD_HOST: xcache
      ORIGIN_HOST: https://origin
      ORIGIN_XRD_PORT: 8443
      CACHE_RAM_GB: 4
    #     REDIR_HOST: localhost
    #     REDIR_CMSD_PORT: 3113
    #     CACHE_LOG_LEVEL: info
    #     CACHE_HTTP_PORT: 8443
    #     STREAMS: 256
    #     LOW_WM: 0.85
    #     HI_WM: 0.95
    #     CACHE_PATH: /data
    #     BLOCK_SIZE: 512k
    #     N_PREFETCH: 0
    links:
    - origin:condemand02.pic.es
  origin:
    build: ../xrootd-escape-http
    hostname: condemand02.pic.es
    environment:
      XRD_HOST: origin
    expose:
    - 8443

